// This Test Port skeleton source file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for Lenard Nagy (elnrnag@elx1pjld12-hz) on Mon Oct 26 08:28:52 2015

// Copyright Ericsson Telecom AB 2000-2014

// You may modify this file. Complete the body of empty functions and
// add your member functions here.

#include "IPv6OverGeoNetworkingPort.hh"

namespace LibItsIpv6OverGeoNetworking__TestSystem {

IPv6OverGeoNetworkingPort::IPv6OverGeoNetworkingPort(const char *par_port_name)
	: IPv6OverGeoNetworkingPort_BASE(par_port_name)
{

}

IPv6OverGeoNetworkingPort::~IPv6OverGeoNetworkingPort()
{

}

void IPv6OverGeoNetworkingPort::set_parameter(const char * parameter_name,
	const char * parameter_value)
{
  TRI_set_param(parameter_name,parameter_value,mp_data);
}

/*void IPv6OverGeoNetworkingPort::Handle_Fd_Event(int fd, boolean is_readable,
	boolean is_writable, boolean is_error) {}*/

void IPv6OverGeoNetworkingPort::Handle_Fd_Event_Error(int fd)
{
  Handle_Fd_Event_Readable(fd);
}

void IPv6OverGeoNetworkingPort::Handle_Fd_Event_Writable(int /*fd*/)
{

}

void IPv6OverGeoNetworkingPort::Handle_Fd_Event_Readable(int fd)
{
    int res=TRI__interface__Types::TRI_read_socket(fd,mp_data.buff);

  if(res<=0){
    TTCN_error("TRI_Mapper connection lost");
  }
  
  TRI__interface__Types::TRI__mapper__PDU pdu;
  
  while(TRI_get_message(mp_data.buff,pdu)){
    switch(pdu.msg().get_selection()){
    case TRI__interface__Types::Msg__union::ALT_enqueue__msg:{
      /**** ****/
      // put the decoder here
      LibItsIpv6OverGeoNetworking__TestSystem::IPv6OverGeoNetworkingInd  data;
       data = TTCN__EncDec::f__dec__IPv6OverGeoNetworkingInd(pdu.msg().enqueue__msg().data().encoded__data());
      /**** ****/
      incoming_message(data);
    }
      break;
    case TRI__interface__Types::Msg__union::ALT_result:
      if(pdu.msg().result().result()==TRI__interface__Types::Result__value::TRI__error){
	TTCN_error("Unsucessfull send");
      }
      break;
    default:
      TTCN_error("Unexpected message");
      break;
    }
  }
}

/*void IPv6OverGeoNetworkingPort::Handle_Timeout(double time_since_last_call) {}*/

void IPv6OverGeoNetworkingPort::user_map(const char * system_port)
{
  TRI_map("GeoNetworkingPort",system_port,mp_data);
  Handler_Add_Fd_Read(mp_data.tri_socket);
}

void IPv6OverGeoNetworkingPort::user_unmap(const char * system_port)
{
  TRI_unmap(mp_data);
  Uninstall_Handler();
}

void IPv6OverGeoNetworkingPort::user_start()
{
  TRI_start("GeoNetworkingPort",get_name(),(component)self,COMPONENT::get_component_name(self),mp_data);
}

void IPv6OverGeoNetworkingPort::user_stop()
{
  TRI_stop(mp_data);
}

void IPv6OverGeoNetworkingPort::outgoing_send(const LibItsIpv6OverGeoNetworking__TestSystem::IPv6OverGeoNetworkingReq& send_par)
{
    TRI__interface__Types::TRI__mapper__PDU pdu;

/**** ****/
// put the encoder here
  pdu.msg().sendmsg().data().encoded__data()=TTCN__EncDec::f__enc__IPv6OverGeoNetworkingReq(send_par);
  /**** ****/

  pdu.msg().sendmsg().addr()=OMIT_VALUE;

  pdu.msg__id()=mp_data.msg_seq_num;
  mp_data.msg_seq_num++;
  
  TRI__interface__Types::TRI_send(mp_data.tri_socket,pdu);


}

} /* end of namespace */

