// This Test Port skeleton header file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for Lenard Nagy (elnrnag@elx1pjld12-hz) on Mon Oct 26 08:28:52 2015

// Copyright Ericsson Telecom AB 2000-2014

// You may modify this file. Add your attributes and prototypes of your
// member functions here.

#ifndef IPv6OverGeoNetworkingPort_HH
#define IPv6OverGeoNetworkingPort_HH

//#include "LibItsIpv6OverGeoNetworking_TestSystem.hh"
#include "TRI_mapper_API.hh"
#include "TTCN_EncDec.hh"

namespace LibItsIpv6OverGeoNetworking__TestSystem {

  class IPv6OverGeoNetworkingPort : public IPv6OverGeoNetworkingPort_BASE {
  public:
    IPv6OverGeoNetworkingPort(const char *par_port_name = NULL);
    ~IPv6OverGeoNetworkingPort();

    void set_parameter(const char *parameter_name,
		       const char *parameter_value);

  private:
    /* void Handle_Fd_Event(int fd, boolean is_readable,
       boolean is_writable, boolean is_error); */
    void Handle_Fd_Event_Error(int fd);
    void Handle_Fd_Event_Writable(int fd);
    void Handle_Fd_Event_Readable(int fd);
    /* void Handle_Timeout(double time_since_last_call); */
  protected:
    TRI__interface__Types::TRI_mapper_data  mp_data;
    void user_map(const char *system_port);
    void user_unmap(const char *system_port);

    void user_start();
    void user_stop();

    void outgoing_send(const LibItsIpv6OverGeoNetworking__TestSystem::IPv6OverGeoNetworkingReq& send_par);
  };

} /* end of namespace */

#endif
