PROJECTROOT  = ..
BUILDROOT    = ../build
PROJECT      = cshared
DEBUG        = yes
testdir      = tests

alibs        = $(PROJECT)
solibs       = $(PROJECT)

sources       := copts.c cserialize.c cstr.c
headers       := copts.h cserialize.h cstr.h
tests         := test_copts.c

include ../common.mk
