// This Test Port skeleton header file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for Lenard Nagy (elnrnag@elx1pjld12-hz) on Thu Oct 22 13:32:32 2015

// Copyright Ericsson Telecom AB 2000-2014

// You may modify this file. Add your attributes and prototypes of your
// member functions here.

#ifndef CamPort_HH
#define CamPort_HH

#include "LibItsCam_TestSystem.hh"
#include "TRI_mapper_API.hh"
#include "TTCN_EncDec.hh"
#include "CAM_Types.hh"

namespace LibItsCam__TestSystem {

  class CamPort : public CamPort_BASE {
  public:
    CamPort(const char *par_port_name = NULL);
    ~CamPort();

    void set_parameter(const char *parameter_name,
		       const char *parameter_value);

  private:
    /* void Handle_Fd_Event(int fd, boolean is_readable,
       boolean is_writable, boolean is_error); */
    void Handle_Fd_Event_Error(int fd);
    void Handle_Fd_Event_Writable(int fd);
    void Handle_Fd_Event_Readable(int fd);
    /* void Handle_Timeout(double time_since_last_call); */
  protected:
    TRI__interface__Types::TRI_mapper_data  mp_data;
    void user_map(const char *system_port);
    void user_unmap(const char *system_port);

    void user_start();
    void user_stop();

    void outgoing_send(const LibItsCam__TestSystem::CamReq& send_par);
  };

} /* end of namespace */

#endif
