######################################################################
##
##  Created by: Denis Filatov
##
##  Copyleft (c) 2015
##  This code is provided under the CeCill-C license agreement.
######################################################################
PROJECTROOT    = ..
BUILDROOT      = ../build
PROJECT        = msgcheck
DEBUG          = yes
bins           = msgcheck
sources       := msgcheck.c
packages      += openssl cshared
include ../common.mk
