// This Test Port skeleton header file was generated by the
// TTCN-3 Compiler of the TTCN-3 Test Executor version CRL 113 200/5 R3A
// for Lenard Nagy (elnrnag@elx1pjld12-hz) on Wed Nov 11 13:57:09 2015

// Copyright Ericsson Telecom AB 2000-2014

// You may modify this file. Add your attributes and prototypes of your
// member functions here.

#ifndef GeoNetworkingPort_HH
#define GeoNetworkingPort_HH

#include "TRI_mapper_API.hh"
#include "TTCN_EncDec.hh"

namespace LibItsGeoNetworking__TestSystem {

  class GeoNetworkingPort : public GeoNetworkingPort_BASE {
  public:
    GeoNetworkingPort(const char *par_port_name = NULL);
    ~GeoNetworkingPort();

    void set_parameter(const char *parameter_name,
		       const char *parameter_value);

  private:
    /* void Handle_Fd_Event(int fd, boolean is_readable,
       boolean is_writable, boolean is_error); */
    void Handle_Fd_Event_Error(int fd);
    void Handle_Fd_Event_Writable(int fd);
    void Handle_Fd_Event_Readable(int fd);
    /* void Handle_Timeout(double time_since_last_call); */
  protected:
    TRI__interface__Types::TRI_mapper_data  mp_data;
    void user_map(const char *system_port);
    void user_unmap(const char *system_port);

    void user_start();
    void user_stop();

    void outgoing_send(const LibItsGeoNetworking__TestSystem::GeoNetworkingReq& send_par);
  };

} /* end of namespace */

#endif
