/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SPAT-ETSI"
 * 	found in "MAP_SPAT_ETSI.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_MAP_PDU_H_
#define	_MAP_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "MapData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MAP-PDU */
typedef struct MAP_PDU {
	ItsPduHeader_t	 header;
	MapData_t	 mapData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAP_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAP_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _MAP_PDU_H_ */
#include <asn_internal.h>
