/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC2"
 * 	found in "DSCR2.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Offset_B12_H_
#define	_Offset_B12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Offset-B12 */
typedef long	 Offset_B12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Offset_B12;
asn_struct_free_f Offset_B12_free;
asn_struct_print_f Offset_B12_print;
asn_constr_check_f Offset_B12_constraint;
ber_type_decoder_f Offset_B12_decode_ber;
der_type_encoder_f Offset_B12_encode_der;
xer_type_decoder_f Offset_B12_decode_xer;
xer_type_encoder_f Offset_B12_encode_xer;
per_type_decoder_f Offset_B12_decode_uper;
per_type_encoder_f Offset_B12_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Offset_B12_H_ */
#include <asn_internal.h>
