/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "REG-D"
 * 	found in "MAP_SPAT_REG_D.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Reg_Position3D_H_
#define	_Reg_Position3D_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Altitude.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Altitude;

/* Reg-Position3D */
typedef struct Reg_Position3D {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct Altitude	*altitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Reg_Position3D_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reg_Position3D;

#ifdef __cplusplus
}
#endif

#endif	/* _Reg_Position3D_H_ */
#include <asn_internal.h>
