/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "REG-D"
 * 	found in "MAP_SPAT_REG_D.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Reg_RestrictionUserType_H_
#define	_Reg_RestrictionUserType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EmissionType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Reg-RestrictionUserType */
typedef struct Reg_RestrictionUserType {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	EmissionType_t	*emission	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Reg_RestrictionUserType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reg_RestrictionUserType;

#ifdef __cplusplus
}
#endif

#endif	/* _Reg_RestrictionUserType_H_ */
#include <asn_internal.h>
