/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRC_REG_D.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_IntersectionGeometry_H_
#define	_IntersectionGeometry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptiveName.h"
#include "IntersectionReferenceID.h"
#include "MsgCount.h"
#include "Position3D-2.h"
#include "LaneWidth.h"
#include "LaneList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedLimitList;
struct PreemptPriorityList;
struct Reg_Intersection;

/* IntersectionGeometry */
typedef struct IntersectionGeometry {
	DescriptiveName_t	*name	/* OPTIONAL */;
	IntersectionReferenceID_t	 id;
	MsgCount_t	 revision;
	Position3D_2_t	 refPoint;
	LaneWidth_t	*laneWidth	/* OPTIONAL */;
	struct SpeedLimitList	*speedLimits	/* OPTIONAL */;
	LaneList_t	 laneSet;
	struct PreemptPriorityList	*preemptPriorityData	/* OPTIONAL */;
	struct Reg_Intersection	*regional	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionGeometry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionGeometry;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SpeedLimitList.h"
#include "PreemptPriorityList.h"
#include "RegionalIntersection.h"

#endif	/* _IntersectionGeometry_H_ */
#include <asn_internal.h>
