/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "REG-D"
 * 	found in "MAP_SPAT_REG_D.asn"
 * 	`asn1c -gen-PER`
 */

#include "Reg-RestrictionUserType.h"

static asn_TYPE_member_t asn_MBR_Reg_RestrictionUserType_1[] = {
	{ ATF_POINTER, 1, offsetof(struct Reg_RestrictionUserType, emission),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EmissionType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"emission"
		},
};
static int asn_MAP_Reg_RestrictionUserType_oms_1[] = { 0 };
static ber_tlv_tag_t asn_DEF_Reg_RestrictionUserType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Reg_RestrictionUserType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* emission */
};
static asn_SEQUENCE_specifics_t asn_SPC_Reg_RestrictionUserType_specs_1 = {
	sizeof(struct Reg_RestrictionUserType),
	offsetof(struct Reg_RestrictionUserType, _asn_ctx),
	asn_MAP_Reg_RestrictionUserType_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_Reg_RestrictionUserType_oms_1,	/* Optional members */
	0, 1,	/* Root/Additions */
	-1,	/* Start extensions */
	2	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Reg_RestrictionUserType = {
	"Reg-RestrictionUserType",
	"Reg-RestrictionUserType",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Reg_RestrictionUserType_tags_1,
	sizeof(asn_DEF_Reg_RestrictionUserType_tags_1)
		/sizeof(asn_DEF_Reg_RestrictionUserType_tags_1[0]), /* 1 */
	asn_DEF_Reg_RestrictionUserType_tags_1,	/* Same as above */
	sizeof(asn_DEF_Reg_RestrictionUserType_tags_1)
		/sizeof(asn_DEF_Reg_RestrictionUserType_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Reg_RestrictionUserType_1,
	1,	/* Elements count */
	&asn_SPC_Reg_RestrictionUserType_specs_1	/* Additional specs */
};

