/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "REG-D"
 * 	found in "MAP_SPAT_REG_D.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Reg_IntersectionState_H_
#define	_Reg_IntersectionState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PrioritizationResponseList;

/* Reg-IntersectionState */
typedef struct Reg_IntersectionState {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct PrioritizationResponseList	*activePrioritizations	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Reg_IntersectionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reg_IntersectionState;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PrioritizationResponseList.h"

#endif	/* _Reg_IntersectionState_H_ */
#include <asn_internal.h>
