/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "MAP-SPAT-ETSI"
 * 	found in "MAP_SPAT_ETSI.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SPAT_PDU_H_
#define	_SPAT_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "SPAT.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SPAT-PDU */
typedef struct SPAT_PDU {
	ItsPduHeader_t	 header;
	SPAT_t	 spatData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SPAT_PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SPAT_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SPAT_PDU_H_ */
#include <asn_internal.h>
